# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aee03a5e5289b7f3ee4aa25a9c2ef0abaad443bf2da92aaac537b7d361ac90f4f5064c21c832162dba13126bcb5589fdcd960cbffc7610db7aff32d76245d3b

test:
  secret_key_base: 3e7a19be2a0902748a7bc54f9c45c17513dea22a421756f4be54dd881ea185a2db97c77b94cb24f3d6250f46212d96218923e61e4e5bfe6121d592282870b357

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
